### PR TITLE
Carthage Support

### PR DESCRIPTION
**Pull request by Prince2k3**
This will need a new release before this will work.

### CODE REVIEW

**Comment by granoff** [comment]
Please bump the version in `Strongbox.podspec` to `0.4`

**Comment by granoff** [comment]
It looks like the `travis.yml` file could be or needs to be updated too, to at least ensure that the Carthage integration works? I've never used Carthage so it's a little difficult to know if your PR is complete. I am basing my comment on the Carthage docs.

**Comment by Prince2k3** [comment]
so my guess after reading the docs is the travis-ci part is for prebuilt frameworks. Should only need to do releases like Cocoapod or tags to get it workings. I was able to get it working on my fork with just the current setup. Any Github releases you do for Cocoapods should also reflect the Carthage builds too.

**Comment by granoff** [comment]
Cool. Well, I'll take your word for it. :-)

**Pull request merged**
