### PR TITLE
Add Carthage installation instructions to README.

### PR DESCRIPTION
**Pull request by SixFiveSoftware**

### CODE REVIEW

**Comment by granoff** [comment]
The .travis.yml file is woefully out of date. I realize your change has no impact on the code, but are you up for updating the .travis.yml file so that CI passes?

**Comment by SixFiveSoftware** [comment]
Sorry, just saw this. I can take a look, I've never used Travis (only Jenkins and GitLab CI, so maybe similar). Gimme a day or two and I'll get back with you. Thanks for the quick response, and your framework!

**Comment by SixFiveSoftware** [comment]
@granoff I just submitted an update, please excuse if it is a shoddy attempt to update. Just bumped the pod version, xcode version, and updated the language. Hope that helps!

**Comment by granoff** [comment]
Thanks. Unfortunately, the CI is still failing. The issue seems to be that `gpg2` cannot be found. Honestly, I am not sure that is even necessary anymore. Can you try just commenting that line out?

**Comment by granoff** [comment]
Actually, try changing `gpg2` to simply `gpg` first. Curious to see if that works. It may in fact be necessary for `rvm`.

**Comment by granoff** [comment]
Okey dokey. I fixed the file, and merged it to `master`. So you can remove your `.travis.yml` changes from this PR, rebase off `master`, and then we'll be good. (You did the heavy lifting on this, I just couldn't contain my curiosity to see if it would be easy to make work again.)

**Comment by SixFiveSoftware** [comment]
Cool, thanks for the update @granoff . I pulled your changes and updated the PR.

**Comment by granoff** [comment]
Thank you!

**Pull request merged**
